WIP: node code updates for multipath device cleanup after use
kubernetes-sigs/ibm-powervs-block-csi-driver pull request #392
Opened 2023-05-03 17:32 UTC by yussufsh

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR changes will handle proper cleanup of disks on nodes and prevent "disk not found" issues. Other features:

1. Upgrade k8s version
2. Replace use of deprecated mount pkg with mount-utils.
3. Handle multipath devices using commands: dmsetup, multipathd.
4. Proper cleanup after using the disks and while searching for new disks.
5. Tests updates for the new code.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Apologies for such a big PR but expecting multiple logical commits will help with the review process.

**Release note**:
```
none
```

2023-05-04 08:24 UTC, mkumatag commented
/ok-to-test

2023-05-04 09:34 UTC, Madhan-SWE commented
/retest

2023-05-05 05:07 UTC, Madhan-SWE commented
/retest

2023-05-05 05:11 UTC, Madhan-SWE commented
/retest

2023-05-05 05:46 UTC, yussufsh commented
This PR is ready for review.

There are couple of `golangci-lint` errors related to this PR which I can fix with the review comments later.
```
pkg/device/multipath.go:275:47: Error return value of `(*os/exec.Cmd).Run` is not checked (errcheck)
					exec.Command("umount", umountArgs...).Run()
					                                         ^
pkg/device/multipath.go:276:47: Error return value of `(*os/exec.Cmd).Run` is not checked (errcheck)
					exec.Command(dmsetupcommand, args...).Run() 
```

Other lint issues does not belong to this PR but will try to fix them as well.
```
 pkg/cloud/powervs.go:193:14: SA1019: pointer.Float64Ptr is deprecated: Use Float64 instead. (staticcheck)
		Size:      pointer.Float64Ptr(float64(capacityGiB)),
		           ^
pkg/util/volume_lock.go:32:8: SA1019: sets.String is deprecated: use generic Set instead. new ways: s1 := Set[string]{} s2 := New[string]() (staticcheck)
	locks sets.String 
```

2023-05-17 14:33 UTC, mkumatag requested changes

2023-05-17 14:33 UTC, mkumatag commented on pkg/device/device.go
> +}
```suggestion
func (d *Device) getLinuxDmDevice(needActivePath bool) error {
	args := []string{"ls", "--target", "multipath"}
	outBytes, err := exec.Command(dmsetupcommand, args...).CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to retrieve multipath devices: %s", out)
	}

	r, err := regexp.Compile(majorMinorPattern)
	if err != nil {
		return fmt.Errorf("unable to compile regex with %s", majorMinorPattern)
	}
	listOut := r.FindAllString(string(outBytes), -1)

	for _, line := range listOut {
		result := findStringSubmatchMap(line, r)

		tmpPathname := "dm-" + result["Minor"]
		uuid, err := getUUID(tmpPathname)
		if err != nil {
			return err
		}
		tmpWWID := strings.TrimPrefix(uuid, "mpath-")
		tmpWWN := tmpWWID[1:] // truncate scsi-id prefix

		if !strings.EqualFold(d.WWN, tmpWWN) {
			continue
		}
		d.WWID = tmpWWID
		mapName, err := getMpathName(tmpPathname)
		if err != nil {
			return err
		}
		d.Mapper = "/dev/mapper/" + mapName

		multipathdShowPaths, err := retryGetPathOfDevice(d, needActivePath)
		if err != nil {
			err = fmt.Errorf("unable to get scsi slaves for device %s: %v", d.WWN, err)
			return err
		}
		for _, path := range multipathdShowPaths {
			if path != nil && (!needActivePath || path.ChkState == "ready") {
				d.Slaves = append(d.Slaves, path.Device)
			}
		}
	}

	return nil
}
```

2023-05-17 14:33 UTC, mkumatag commented on pkg/device/device.go
> +}
```suggestion
func (d *Device) CreateDevice() error {
	if err := scsiHostRescan(); err != nil {
		return err
	}
	// wait for device to appear after rescan
	time.Sleep(time.Second * 1)

	if err := d.createLinuxDevice(); err != nil {
		klog.Errorf("unable to create device for wwn %v", d.WWN)
		return err
	}

	if d.Mapper == "" {
		return fmt.Errorf("unable to find the device for wwn %s", d.WWN)
	}
	return nil
}
```

2023-05-17 15:53 UTC, yussufsh commented on pkg/device/multipath.go
> +	showMapsFormat   = []string{"show", "maps", "format", "%w %d %n %s"}
I was trying this before not sure why I reverted back. May be empty output failures. This will need thorough testing.

2023-05-17 16:10 UTC, yussufsh commented on pkg/device/multipath.go
> +		}
Agreed. Had kept it to put some warning logs, but it becomes noisy. Completely removed the check.

2023-05-17 16:12 UTC, yussufsh commented on pkg/device/device.go
> +}
let's go with chatgpt then.

2023-05-17 16:16 UTC, yussufsh commented on pkg/device/multipath.go
> +		err := deleteSdDevice(deletePath)
I was not able to grep the device names via regex. `hcil` was easy to grep because of `:` in them hence using it directly.

2023-05-19 10:11 UTC, yussufsh commented on pkg/device/device.go
> +		if i%2 == 0 {
Yup, this was the previous logic I used to do 1 each time. Both are not needed I will remove this check.

2023-05-19 13:56 UTC, mkumatag approved these changes
/lgtm
/approve

2023-05-19 13:58 UTC, merged