Using env vars for getting the metadata details
kubernetes-sigs/ibm-powervs-block-csi-driver pull request #463
Opened 2023-09-07 09:27 UTC by yussufsh

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This will help with running the driver tests locally. Currently, it relies on k8s cluster node.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
none
```

2023-09-07 09:44 UTC, yussufsh commented
/retest

2023-09-14 06:06 UTC, mkumatag requested changes
And also add some document around what we are trying to achieve for these modifications like some text talking about integration tests and how to run them etc..

2023-09-14 06:06 UTC, mkumatag commented on pkg/driver/controller.go
> +	cID := os.Getenv("POWERVS_CLOUD_INSTANCE_ID")
Please add a comment here with all the detail why we are adding these variables

2023-09-14 06:06 UTC, mkumatag commented on pkg/driver/node.go
> +	cID := os.Getenv("POWERVS_CLOUD_INSTANCE_ID")
Please add a comment here with all the detail why we are adding these variables

2023-09-14 06:37 UTC, yussufsh commented
> And also add some document around what we are trying to achieve for these modifications like some text talking about integration tests and how to run them etc..

I will add the docs for running IT when the framework is ready.
For now, added comments. PTAL again.

2023-09-14 06:38 UTC, mkumatag approved these changes
/lgtm

2023-09-14 06:48 UTC, merged